### ISSUE TITLE
Problem with running a tournament Cleopetra

### ISSUE THREAD

**Issue by Repchic** [ds306e18/cleopetra#126]
[Doc2.docx](https://github.com/ds306e18/cleopetra/files/8908816/Doc2.docx)

I have a problem with running a tournament. I've installed RLBotGUI and Cleopetra. But when I try to start a tournament match the Cleopetra console appears on 1 sec and  disappears, after that there is a sign at the bottom and anything happens. JAVA JDK and RLBot framework are installed. Please help! Screenshots are in the file.

**Comment by NicEastvillage** [comment]
To really understand the problem I need to know what the CleoPetra console says. But first, answer these:
* Have you tried starting a tournament, while RLBotGUI was closed?
* Do you have Steam or Epic version of Rocket League?
* What is your RLBot settings? (screenshot of the RLBot Settings tab)
