### ISSUE TITLE
Running test should not create junk in main directory

### ISSUE THREAD

**Issue by NicEastvillage** [ds306e18/cleopetra#17]
Running tests currently creates some new files in the main directory. These should be in the test folder or deleted afterwards. The files are: `tournamentSystem.obj`

Also the file `testconfig.cfg` should recide in a test resources folder

**Comment by cogitantium** [comment]
Agreed. The _junk_ is included in `.gitignore` though, so not a huge problem.

**Comment by cogitantium** [comment]
The existing junk test-files generated by running tests are; 
```
dummyconfig.cfg
filename.obj
filename.object
tournamentState.obj
```
`testconfig.cfg` is a copy of a RLBot-framework config for testing the functionality of `ConfigFileEditor`. This resource should recide in `/test/resources/`.

**Comment by cogitantium** [comment]
Maybe the `testconfig.cfg` should rather reside in in `/test/` as a dir would imply a package.
