### ISSUE TITLE
Expand functionality of ConfigFileEditor

### ISSUE THREAD

**Issue by NicEastvillage** [ds306e18/cleopetra#3]
I imagine that the `ConfigFileEditor` class is replaced with a `RLBotConfig` that encapsulates the `rlbot.cfg`. It has methods like:
```java
class RLBotConfig {
    public RLBotConfig(Path);
    public void save();
    public boolean setupMatch(Match);
    public void setParticipantConfig(Path or String, participantIndex)
    public void setParticipantType(Human|Bot|Psyonix, participantIndex)
    public void setParticipantTeam(teamIndex, participantIndex)
    // etc
}
```

Previous title was: "Use an INI config parser library instead of home made config parser"

**Comment by cogitantium** [comment]
Would a `configureMatch(Match match)`-method still be relevant, as to not break previous CFE-calls?

**Comment by NicEastvillage** [comment]
I don't see why it wouldn't be relevant. I just called it `setupMatch(Match)` in the example of the issue description.

**Comment by cogitantium** [comment]
Through discussion it has been decided that there's no need to use a proper INI-parser library, as the best contender for this purpose, `ini4j`, changes formatting of the given ini-file, which is undesired behaviour. 
However, the CFE-class will be reworked to provide extended functionality on both `rlbot.cfg`s and `bot.cfg`s, such that fields in "participant settings" can potentially be auto-filled by CleoPetra.
