### ISSUE TITLE
Unit test "testRoundRobinBracket03" takes a relatively long time

### ISSUE THREAD

**Issue by cogitantium** [ds306e18/cleopetra#43]
`testRoundRobinBracket03` takes 3.7s on my `4600U`, where the three other `testRoundRobinBracket`-tests takes 0ms. Something is wrong with either the test or the round-robin implementation.

This is a low priority issue, as this is only an efficiency-bug and not a correctness-bug.

**Comment by NicEastvillage** [comment]
Lol. It is not a bug though. But 1234 teams are quite many.

**Comment by cogitantium** [comment]
Ah, of course. Maybe this should be reduced to a more sane value. It's a shame that this single test takes up 75% of the runtime of the test suite.

**Comment by NicEastvillage** [comment]
Agree
