### ISSUE TITLE
FileChooser-dialog assumes user-folder "Documents"

### ISSUE THREAD

**Issue by cogitantium** [ds306e18/cleopetra#75]
In the SaveLoad class, the `lastSavedDirectory` string is badly named, as it statically sets the initial location of the FileChooser-dialog to `$user/Documents`.

In my case, on a Linux machine, I do not have a Documents folder in my home directory. Luckily the `System.getProperty("user.home")` is accurately able to find the path to my user, which would be `/home/$user/` on all GNU/LINUX-systems, as far as I recall.

The offending line:
```java
public static File lastSavedDirectory = new File(System.getProperty("user.home") + (File.separatorChar + "Documents"));
```

A better approach would be to start the dialog in the `$user` directory initially, as all users must have a user-dir, regardless of operating system and preferences. Upon subsequent calls, the dialog should start in the lastly accessed folder for ease of use, however, this may be less important as a user likely only saves once during each run of the system.

**Comment by NicEastvillage** [comment]
Good call. Also, currently the bot config file chooser and the save tournament file chooser have two different `lastSavedDirectory` variables, but I usually find that my RLBot stuff (bots and tournament files) are located either in the same folder or very close, so I suggest making them share the `lastSavedDirectory` now we are at it.

**Comment by NicEastvillage** [comment]
Accidentally closed the issue. Opened again!

**Comment by cogitantium** [comment]
Whoops!

I agree though. We should assume that the user is using locality on their stuff.
